package com.ahs.common.error;

public enum ErrorKey {
    ROUTE_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    RATE_LIMIT_EXCEEDED,
    SERVICE_UNAVAILABLE,

    INVALID_REQUEST,
    VALIDATION_FAILED,

    INVALID_CREDENTIALS,
    ACCESS_TOKEN_EXPIRED,
    REFRESH_TOKEN_EXPIRED,
    INSUFFICIENT_PERMISSION,
    AUTHENTICATION_FAILED,

    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,

    CAMERA_NOT_FOUND,
    CAMERA_OFFLINE
}